name: interbank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Animasyonlu GIF için
  gif_view: ^0.3.1
  # (İstersen kullanırsın; şart değil)
  flutter_gif: ^0.0.4

  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  connectivity_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/chatbot/404_hata.png
    - lib/assets/images/chatbot/tele_sekreter.png
    - lib/assets/images/chatbot/smile.png
    - lib/assets/images/chatbot/thinking.png
    - lib/assets/images/chatbot/kalpli.png
    - lib/assets/images/chatbot/baglanti.png
    - lib/assets/images/person/teamwork.png
    - lib/assets/gifs/rudder.gif
    - lib/assets/images/chatbot/icons8-captain-48.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: lib/assets/fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
