name: interbank 
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  connectivity_plus: ^6.0.1
  http: ^1.1.0  # YENİ EKLENEN PAKET
  shared_preferences: ^2.5.3
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4   # 👈 EKLENDİ

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/bnk.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/icons/bnk.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/chatbot/404_hata.png
    - lib/assets/images/chatbot/tele_sekreter.png
    - lib/assets/images/chatbot/smile.png
    - lib/assets/images/chatbot/thinking.png
    - lib/assets/images/chatbot/kalpli.png
    - lib/assets/images/chatbot/baglanti.png
    - lib/assets/images/person/teamwork.png

    - lib/assets/images/captain/
    - lib/assets/images/captain/captain.png
    - lib/assets/images/captain/captain_writing.png
    - lib/assets/images/captain/captain_thinking.png
    - lib/assets/images/captain/captain_sekreter.png
    - lib/assets/images/captain/captain_noconnection.png
    - lib/assets/images/captain/captain_connection.png

    - lib/assets/images/captain/hat/
    - lib/assets/images/captain/hat/hat_idle.png
    - lib/assets/images/captain/hat/hat_peek_0.png
    - lib/assets/images/captain/hat/hat_peek_1.png
    - lib/assets/images/captain/hat/hat_peek_2.png
    - lib/assets/images/captain/hat/hat_peek_3.png

    - lib/assets/images/captain/home/
    - lib/assets/images/captain/home/apps.png
    - lib/assets/images/captain/home/home.png
    - lib/assets/images/captain/home/pay.png
    - lib/assets/images/captain/home/send.png

    - lib/assets/images/captain/login/
    - lib/assets/images/captain/login/Sea-Background.jpeg

    - lib/assets/images/captain/chat/
    - lib/assets/images/captain/chat/Chatbot-Background.jpeg

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: lib/assets/fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
